// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "vitorinomuller@gmail.com"
        },
        "license": {
            "name": "Stone Co®."
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "post": {
                "description": "With the data received, validate her and if all is correct, and dont exist a account with that document, create a new account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "Account Creation Data",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/input.CreateAccountVO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/balance": {
            "get": {
                "description": "With a authorization token valid, return the balance of a account",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization Token",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/account/login": {
            "post": {
                "description": "With the data received, validate if is correct, and log the user, returning a token of authorization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "Account Login Data",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/input.LoginVO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/accounts": {
            "get": {
                "description": "Get all accounts actually in the system",
                "produces": [
                    "application/json"
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "input.CreateAccountVO": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer",
                    "example": 1000
                },
                "cpf": {
                    "type": "string",
                    "example": "600.246.058-67"
                },
                "name": {
                    "type": "string",
                    "example": "João da Silva"
                },
                "secret": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "input.LoginVO": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string",
                    "example": "600.246.058-67"
                },
                "secret": {
                    "type": "string",
                    "example": "123456"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8000",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "stoneBanking API",
	Description: "This is a simples application to create accounts and transfers between valide accounts",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
