definitions:
  input.CreateAccountVO:
    properties:
      balance:
        example: 1000
        type: integer
      cpf:
        example: 600.246.058-67
        type: string
      name:
        example: João da Silva
        type: string
      secret:
        example: "123456"
        type: string
    type: object
  input.LoginVO:
    properties:
      cpf:
        example: 600.246.058-67
        type: string
      secret:
        example: "123456"
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: vitorinomuller@gmail.com
    name: API Support
  description: This is a simples application to create accounts and transfers between
    valide accounts
  license:
    name: Stone Co®.
  title: stoneBanking API
  version: "1.0"
paths:
  /account:
    post:
      consumes:
      - application/json
      description: With the data received, validate her and if all is correct, and
        dont exist a account with that document, create a new account
      parameters:
      - description: Account Creation Data
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/input.CreateAccountVO'
      produces:
      - application/json
      responses: {}
  /account/balance:
    get:
      description: With a authorization token valid, return the balance of a account
      parameters:
      - description: Authorization Token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
  /account/login:
    post:
      consumes:
      - application/json
      description: With the data received, validate if is correct, and log the user,
        returning a token of authorization
      parameters:
      - description: Account Login Data
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/input.LoginVO'
      produces:
      - application/json
      responses: {}
  /accounts:
    get:
      description: Get all accounts actually in the system
      produces:
      - application/json
      responses: {}
swagger: "2.0"
