definitions:
  input.CreateAccountVO:
    properties:
      balance:
        example: 1000
        type: integer
      cpf:
        example: 600.246.058-67
        type: string
      name:
        example: João da Silva
        type: string
      secret:
        example: "123456"
        type: string
    type: object
  input.CreateTransferVO:
    properties:
      account_destiny_id:
        example: "3"
        type: string
      account_origin_id:
        example: "2"
        type: string
      amount:
        example: 1000
        type: integer
    type: object
  input.LoginVO:
    properties:
      cpf:
        example: 600.246.058-67
        type: string
      secret:
        example: "123456"
        type: string
    type: object
  output.AccountBalanceVO:
    properties:
      balance:
        example: 12.34
        type: number
    type: object
  output.AccountOutputVO:
    properties:
      balance:
        example: 10
        type: number
      cpf:
        example: 600.246.058-67
        type: string
      created_at:
        example: 12/05/2021 00:01:01
        type: string
      id:
        example: "123"
        type: string
      name:
        example: João da Silva
        type: string
    type: object
  output.LoginOutputVO:
    properties:
      authorization:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        type: string
    type: object
  output.TransferOutputVO:
    properties:
      account_destiny_id:
        example: bf89f445-70d3-442f-9821-55699a868704
        type: string
      account_origin_id:
        example: bf89f445-70d3-442f-9821-55699a868704
        type: string
      created_at:
        example: 12/05/2021 00:01:01
        type: string
      id:
        example: bf89f445-70d3-442f-9821-55699a868704
        type: string
      value:
        example: 123.32
        type: number
    type: object
  stoneBanking_app_gateway_http_account_vo_output.OutputError:
    properties:
      error:
        example: error
        type: string
    type: object
  stoneBanking_app_gateway_http_transfer_vo_output.OutputError:
    properties:
      error:
        example: error
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: vitorinomuller@gmail.com
    name: API Support
  description: This is a simples application to create accounts and transfers between
    valide accounts
  license:
    name: Stone Co®.
  title: stoneBanking API
  version: "1.0"
paths:
  /accounts:
    get:
      description: Get all accounts actually in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/output.AccountOutputVO'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_account_vo_output.OutputError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_account_vo_output.OutputError'
    post:
      consumes:
      - application/json
      description: With the data received, validate her and if all is correct, and
        dont exist a account with that document, create a new account
      parameters:
      - description: Account Creation Data
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/input.CreateAccountVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/output.AccountOutputVO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_account_vo_output.OutputError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_account_vo_output.OutputError'
  /accounts/balance:
    get:
      description: With a authorization token valid, return the balance of a account
      parameters:
      - description: Authorization Token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/output.AccountBalanceVO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_account_vo_output.OutputError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_account_vo_output.OutputError'
  /login:
    post:
      consumes:
      - application/json
      description: With the data received, validate if is correct, and log the user,
        returning a token of authorization
      parameters:
      - description: Account Login Data
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/input.LoginVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/output.LoginOutputVO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_account_vo_output.OutputError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_account_vo_output.OutputError'
  /transfer:
    post:
      consumes:
      - application/json
      description: With the data received, validate her and if all is correct, create
        a new transfer, and update the balance of accounts
      parameters:
      - description: Authorization Token
        in: header
        name: authorization
        required: true
        type: string
      - description: Transfer Creation Data
        in: body
        name: transfer
        required: true
        schema:
          $ref: '#/definitions/input.CreateTransferVO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/output.TransferOutputVO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_transfer_vo_output.OutputError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_transfer_vo_output.OutputError'
  /transfers:
    get:
      consumes:
      - application/json
      description: With a valid Authorization Token, get all the transfers that has
        made or received by the account
      parameters:
      - description: Authorization Token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/output.TransferOutputVO'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_transfer_vo_output.OutputError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/stoneBanking_app_gateway_http_transfer_vo_output.OutputError'
swagger: "2.0"
